# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PCA_PostExc
                                 A QGIS plugin
 This plugin helps during the postex phase
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-25
        copyright            : (C) 2022 by Valerio Pinna
        email                : pinnavalerio@yahoo.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PCA_PostExc class from file PCA_PostExc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pca_postex import PCA_PostExc
    return PCA_PostExc(iface)
